-- Drop and recreate Records table

DROP TABLE IF EXISTS records CASCADE;
CREATE TABLE records (
  id SERIAL PRIMARY KEY NOT NULL,
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  game_id INTEGER REFERENCES games(id) ON DELETE CASCADE
);
